# Generated by Django 5.0.6 on 2024-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtde_estoque', models.IntegerField()),
                ('qtde_min', models.IntegerField()),
                ('data_valdiade', models.DateField()),
            ],
        ),
    ]
