# Generated by Django 5.0.6 on 2024-06-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_valdiade',
            new_name='data_validade',
        ),
    ]
