# Generated by Django 5.0.6 on 2024-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=52, null=True)),
                ('qtde', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_validade', models.DateField()),
                ('data_compra', models.DateField()),
                ('Produto', models.ManyToManyField(to='produtos.produto')),
                ('fornecedor', models.ManyToManyField(to='fornecedores.fornecedor')),
            ],
        ),
    ]
