# Generated by Django 5.0.6 on 2024-06-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='preco',
        ),
        migrations.AddField(
            model_name='compra',
            name='protocolo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
