# Generated by Django 5.0.6 on 2024-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='indentificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
