# Generated by Django 5.0.6 on 2024-06-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_indentificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='indentificador',
            new_name='identificador',
        ),
    ]
