# Generated by Django 5.0.6 on 2024-06-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_compra_preco_compra_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
