# Generated by Django 5.0.6 on 2024-06-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
