# Generated by Django 5.0.6 on 2024-06-11 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_rename_indentificador_compra_identificador'),
        ('fornecedores', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Produto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor'),
        ),
    ]
