# Generated by Django 5.0.6 on 2024-06-10 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_protocolo'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data_validade',
            new_name='data_compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='qtde',
        ),
        migrations.AlterField(
            model_name='compra',
            name='descricao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('data_validade', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='item_compra',
            field=models.ManyToManyField(to='compras.itemcompra'),
        ),
    ]
